[build]
target = "./index.html"

[watch]
# this stops trunk from rebuilding twice after tailwind modifies styles.css
ignore = ["./src-tauri", "./styles.css"] 

[serve]
address = "127.0.0.1"
port = 1420
open = false

# This is a nushell specific configuration (comment this out if on other shells)
[[hooks]]
stage = "pre_build"
command = "nu"
command_arguments = ["-c", "npx tailwindcss -i ./src/tailwind.css -o ./styles.css"]

# # you will need to uncomment this for most shells
# [[hooks]]
# stage = "pre_build"
# command = "npx"
# command_arguments = ["tailwindcss -i ./src/input.css -o ./output.css"]
